version: '3.8'

services:
  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - python-app

  python-app:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app